<?php

namespace ExerciseBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * KnightRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KnightRepository extends EntityRepository
{
}
